# Notes on NumPy

Why use numpy?
- NumPy provides efficient storage
- It also provides better ways of handling data for processing
- It is fast
- It is easy to learn
- NumPy uses relatively uses less memory to store data

In [1]:
import numpy as np

Create an array

In [6]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [8]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [9]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [11]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [12]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [16]:
#2 rows and 5 columns
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
#linspace is linearly spaced point in the given range with a specified step size
np.linspace(0,20,10)# It gives 10 equal parts between 0 and 20 

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [18]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [19]:
np.eye(5,dtype=int) #Gives identity matrix of size 5

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [20]:
np.random.rand(2,4) #gives a random array of 2 rows and 4 columns

array([[0.43564087, 0.0410702 , 0.02682106, 0.17102373],
       [0.70346248, 0.10524672, 0.29850992, 0.0470321 ]])

In [21]:
np.random.randn(2,4) #includes negative number as well

array([[ 0.00984653,  0.43172556, -1.34009849, -0.38072067],
       [ 0.68327487, -0.47993996, -0.7333819 ,  0.76371857]])

In [22]:
np.random.randint(0,10,15) # Creates an array of size 15 with values 0 to 9 

array([6, 1, 6, 2, 9, 0, 7, 9, 0, 6, 7, 0, 5, 5, 5])

In [25]:
np.random.randint(10,50,20)

array([39, 21, 42, 28, 13, 29, 48, 35, 39, 36, 14, 21, 33, 41, 11, 13, 38,
       49, 12, 43])

In [24]:
rand_array= np.random.randint(0,10,5)
rand_array

array([0, 3, 5, 5, 0])

In [27]:
sample=np.arange(3,30)
sample

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
sample.min()

3

In [29]:
sample.argmin() #index of the minimum value

0

In [30]:
sample.max()

29

In [31]:
sample.argmax()

26

In [33]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
b=np.random.rand(3,6)
b

array([[0.68495862, 0.96093694, 0.00606156, 0.35457811, 0.34236329,
        0.2611078 ],
       [0.82781967, 0.39902671, 0.08043005, 0.68884062, 0.46975278,
        0.65595698],
       [0.64755861, 0.48839169, 0.38496293, 0.20745996, 0.5077421 ,
        0.25711199]])

In [36]:
b.T

array([[0.68495862, 0.82781967, 0.64755861],
       [0.96093694, 0.39902671, 0.48839169],
       [0.00606156, 0.08043005, 0.38496293],
       [0.35457811, 0.68884062, 0.20745996],
       [0.34236329, 0.46975278, 0.5077421 ],
       [0.2611078 , 0.65595698, 0.25711199]])

In [40]:
c_samp=np.arange(1,16)
c_samp

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
c_samp=c_samp.reshape(3,5)
c_samp

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [44]:
c_samp=c_samp.reshape(5,3)
c_samp

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [45]:
c_samp=c_samp.ravel()
c_samp

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
c_samp=c_samp.reshape(3,5)
c_samp

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [48]:
c_samp[1]=50
c_samp

array([[ 1,  2,  3,  4,  5],
       [50, 50, 50, 50, 50],
       [11, 12, 13, 14, 15]])

In [50]:
d_samp=np.arange(9,26)
d_samp

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [52]:
d_samp[:]=200
d_samp

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200])

In [51]:
sub_d_samp=d_samp[2:6]
sub_d_samp

array([11, 12, 13, 14])

# 2-D Array

In [55]:
two_ar=np.array(([13,23,45],[65,43,54],[98,23,54]))
two_ar

array([[13, 23, 45],
       [65, 43, 54],
       [98, 23, 54]])

In [57]:
two_ar[1][2]

54

In [58]:
two_ar[:,2]

array([45, 54, 54])

In [59]:
two_ar[0:1,1:2]

array([[23]])

In [83]:
two_ar.sum(axis=0)

array([176,  89, 153])

In [84]:
two_ar.sum(axis=1)

array([ 81, 162, 175])

In [94]:
two_ar.argmax()

6

In [95]:
two_ar.argmin()

0

In [96]:
two_ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [97]:
two_ar.argmax(axis=1)

array([2, 0, 0], dtype=int64)

In [98]:
two_ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 2, 1],
       [2, 1, 2]], dtype=int64)

In [99]:
np.where(two_ar>54)

(array([1, 2], dtype=int64), array([0, 0], dtype=int64))

In [100]:
np.count_nonzero(two_ar)

9

In [85]:
two_ar.flat #gets an iterator

In [87]:
for item in two_ar.flat:
    print(item)

13
23
45
65
43
54
98
23
54


In [89]:
two_ar.ndim #No. of dimensions

2

In [90]:
two_ar.size

9

In [91]:
two_ar.nbytes # total bytes consumed

36

In [92]:
one_ar=np.array([5,4,9,6,34,2,3])
one_ar

array([ 5,  4,  9,  6, 34,  2,  3])

In [93]:
one_ar.argsort() 

array([5, 6, 1, 0, 3, 2, 4], dtype=int64)

In [61]:
f_eg=np.arange(2,15)
f_eg

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
f_eg+f_eg

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [63]:
np.exp(f_eg)

array([7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
       2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06])

In [64]:
np.sqrt(f_eg)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739])

In [65]:
np.log(f_eg)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527,
       2.48490665, 2.56494936, 2.63905733])

In [66]:
np.max(f_eg)

14

In [67]:
np.min(f_eg)

2

In [69]:
np.argmax(f_eg)

12

In [70]:
np.argmin(f_eg)

0

In [72]:
np.square(f_eg)

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196],
      dtype=int32)

In [73]:
np.std(f_eg)

3.7416573867739413

In [74]:
np.var(f_eg)

14.0

In [75]:
np.mean(f_eg)

8.0

In [77]:
np.median(f_eg)

8.0

In [79]:
ar=np.random.randn(4,3)
ar

array([[-0.72406943, -0.78289532,  1.19735683],
       [-0.77455733,  1.52870186, -1.24069551],
       [ 0.24682711,  1.17469678, -0.44556593],
       [ 0.92579631, -0.41451964, -0.18592639]])

In [80]:
np.round(ar,decimals=2)

array([[-0.72, -0.78,  1.2 ],
       [-0.77,  1.53, -1.24],
       [ 0.25,  1.17, -0.45],
       [ 0.93, -0.41, -0.19]])

In [82]:
sp=np.array(['hockey','tennis','cricket','hockey','cricket'])
np.unique(sp)

array(['cricket', 'hockey', 'tennis'], dtype='<U7')

In [3]:
lst=[1,2,3,4,5,500]
sample_list=np.array(lst)
sample_list

array([  1,   2,   3,   4,   5, 500])

In [4]:
np.mean(sample_list)

85.83333333333333

In [5]:
np.median(sample_list)

3.5

For more functions of NumPy refer following:
https://www.w3schools.com/python/numpy/default.asp
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html